name: create-new-release
run-name: create-release-${{ github.ref_name }}
on:
    push:
        tags: 'v*.*.*'

    pull_request:
        branches: main

jobs:
    build-stable-pex-file:
        name: Setting up Python Environment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python Environment
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
                architecture: x64
            
            - name: Install Python Dependencies
              run: pip install -r build-req.txt

            - name: Build Wheel for Package
              run: pip wheel -w . .

            - name: Create Dist Folder
              run: mkdir dist/

            - name: Build Pex File From Stable Code
              run: pex --python=python -f $PWD -r hello/requirements.txt hello -e hello.main -o dist/hello-${{ github.ref_name }}.pex -v
            
            - name: Upload Pex File as Artifact
              uses: actions/upload-artifact@v3
              with:
                name: hello.pex
                path: dist/hello-${{ github.ref_name }}.pex
    
    create-new-release:
        name: Create New Release
        needs: build-stable-pex-file
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Create download folder
              run: mkdir download/

            - name: Download Pex File 
              uses: actions/download-artifact@v3
              id: download
              with: 
                name: hello.pex
                path: hello-${{ github.ref_name }}.pex
                
            - name: Create a new release for stable
              uses: softprops/action-gh-release@v1
              with:
                files: hello-${{ github.ref_name }}.pex